### ISSUE TITLE
Doubts about assessment metrics in dissertations

### ISSUE THREAD

**Issue by MeycL** [HKUDS/DCRec#3]
Thank you very much for your frequent work. Here are the results of my reproduction training, the evaluation metrics are recall and NDCG, while the paper results show HR and NDCG, and the recall value of the code training is very close to the HR, is it a problem of the code, or a clerical error of the paper? This is rather confusing to me.
![image](https://github.com/HKUDS/DCRec/assets/96134259/8b40f013-4507-4b79-b966-86d47c9c803c)
![image](https://github.com/HKUDS/DCRec/assets/96134259/3a1eb10a-e340-4926-94bf-78e5ecdb4cbe)

**Comment by yuh-yang** [comment]
Hi,

HR is equivalent to Recall when it comes with only 1 ground truth.
